FROM alpine
WORKDIR /KrakenPredictor/AssetClient
COPY . .
RUN apk add gcompat && apk add ca-certificates
ENTRYPOINT ./main -pair ${PAIR_ENV}

#docker build --no-cache -t watchmejump/krakenpredictor/assetclient:0.0.3 --build-arg PAIR_ENV=Unknown .
#docker run --net krakenNetwork -e PAIR_ENV=XBTUSDC watchmejump/krakenpredictor/assetclient:0.0.3

#env GOOS=linux GOARCH=amd64 go build *.go