FROM alpine
WORKDIR /KrakenPredictor/DataFetching/Client
COPY . .
RUN apk add gcompat && apk add ca-certificates
ENTRYPOINT ./Client


#ENTRYPOINT /KrakenPredictor/Client/KrakenPredictor

#docker build --no-cache -t watchmejump/krakenpredictor/client:0.0.1 .
#docker run -d --net netPredictor watchmejump/krakenpredictor/client:0.0.1

#env GOOS=linux GOARCH=amd64 go build *.go