/****** Object:  Database [KrakenDB]    Script Date: 9/25/2022 4:06:25 PM ******/
DROP DATABASE [KrakenDB]
GO
/****** Object:  Database [KrakenDB]    Script Date: 9/25/2022 4:06:25 PM ******/
CREATE DATABASE [KrakenDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KrakenDB', FILENAME = N'/var/opt/mssql/data/KrakenDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KrakenDB_log', FILENAME = N'/var/opt/mssql/data/KrakenDB_log.ldf' , SIZE = 335872KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [KrakenDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KrakenDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KrakenDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KrakenDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KrakenDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KrakenDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KrakenDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [KrakenDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [KrakenDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KrakenDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KrakenDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KrakenDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KrakenDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KrakenDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KrakenDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KrakenDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KrakenDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [KrakenDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KrakenDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KrakenDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KrakenDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KrakenDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KrakenDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KrakenDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KrakenDB] SET RECOVERY FULL 
GO
ALTER DATABASE [KrakenDB] SET  MULTI_USER 
GO
ALTER DATABASE [KrakenDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KrakenDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KrakenDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KrakenDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KrakenDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KrakenDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'KrakenDB', N'ON'
GO
ALTER DATABASE [KrakenDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [KrakenDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 400)
GO