FROM debian
WORKDIR /KrakenPredictor/Server
COPY . .
RUN apt-get update
RUN apt-get install ca-certificates curl gnupg lsb-release
RUN apt-get update
RUN apt install openjdk-17-jdk


#ENTRYPOINT go run *.go

#docker run -v /var/run/docker.sock:/var/run/docker.sock -i -t --name pairServer debian

#docker build -t watchmejump/krakenpredictor/pairserver:0.0.1 .