FROM debian
WORKDIR /KrakenPredictor/DataFetching/Server
COPY . .
RUN apt-get -y update
RUN apt-get -y install ca-certificates curl gnupg lsb-release
RUN apt -y install openjdk-17-jdk


#ENTRYPOINT go run *.go

#docker run -v /var/run/docker.sock:/var/run/docker.sock -i -t --name pairServer debian

#docker build -t watchmejump/krakenpredictor/pairserver:0.0.1 .