FROM debian
WORKDIR /KrakenPredictor/DataFetching/Server
COPY . .
RUN apt-get -y update
RUN apt-get -y install ca-certificates curl gnupg lsb-release
RUN apt -y install openjdk-17-jdk
ENTRYPOINT java -jar ClientCoordinator-V0.0.1.jar

#docker run --name FetchServer --net netPredictor --ip 172.100.0.10 -p 8080:8080 -d watchmejump/krakenpredictor/server:0.0.1

#docker build -t watchmejump/krakenpredictor/server:0.0.1 .