FROM debian
WORKDIR /KrakenPredictor/Server
COPY . .
RUN apt-get update
RUN apt-get install ca-certificates curl gnupg lsb-release
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update
RUN apt-get install docker-ce-cli
RUN apt install openjdk-17-jdk


#ENTRYPOINT go run *.go

#docker run -v /var/run/docker.sock:/var/run/docker.sock -i -t --name pairServer debian

#docker build -t watchmejump/krakenpredictor/pairserver:0.0.1 .