FROM debian
WORKDIR /KrakenPredictor/AssetClient
COPY . .
RUN apt-get install ca-certificates -y
ENTRYPOINT ./AssetClient -pair ${PAIR_ENV}

#docker build -t watchmejump/krakenpredictor/assetclient:0.0.2 --build-arg PAIR_ENV=Unknown .
#docker run --net krakenNetwork -e PAIR_ENV=XBTUSDC watchmejump/krakenpredictor/assetclient:0.0.2

#env GOOS=linux GOARCH=amd64 go build *.go